### ISSUE TITLE
DALEXverse 0.19.8 release summer 2019

### ISSUE THREAD

**Issue by pbiecek** [ModelOriented/DALEXtra#16]
DALEXverse 0.19.8 release summer 2019

# Integration

- [x] readability: vignettes
- [x] readability: NEWS
- [x] readability: DESCRIPTION
- [ ] consistency: pkgdown website
- [x] consistency: entry at DrWhy.AI webpage

assigned: @pbiecek

# Code review

- [x] consistency: names of functions 
- [x] consistency: names of files
- [x] consistency: names of variables in functions (local and global)
- [x] length: functions
- [x] readability: code (comments, constructions)

assigned: @hbaniecki  

# Feature review

- [x] readability: documentation (title, description, details)
- [x] readability: examples (relevant, complete, with comments)
- [x] reproducibility: tests (code coverage)
- [x] links to functions: \code 

assigned: @WojciechKretowicz

**Comment by WojciechKretowicz** [comment]
* in your vignette there is a pictures that are not loaded, using mozilla, ubuntu
* sentence *There is no big difference bewtween Python versions when downloading conda therefore it is recommended to choose Python 3.7 (newer Anaconda version) and then downloading python 2.7.* is completely ununderstandable for me
* in my opinion you could more describe the paragraph **Packages useful with explanations**, what are these packages, if they are necessary 
* spelling in **loading data** paragraph *proviede* -> *provide*, *targer* -> *target*
* there is colloquialism in **loading data**, *scikit-learn models do not like it*
* the description of the `explain_scikitlearn` arguments in the main vignette could be moved to the top of the paragraph in my opinion
* i think good idea is to put a link to dalex, at the beginning and in *Creating explanations* paragraph
* 2 spellings in first sentence of *Create your conda virtual env with DALEX*
* example in *Create your conda virtual env with DALEX* is very confusing for me
* whole description of the `create_env` could be more accurate in my opinion
* spelling in **Create explainer from your h2o model** in `data` and `precalculate` parameters description
* in **Wrapper for Python Keras Models** *easy* -> *easily
* in **Wrapper for Python Keras Models**'s *Conda cannot find specified packages at channels you have provided.* there is *Of of*
* in **explain scikit learn** there is no machine code

**Comment by hbaniecki** [comment]
1. file names
- `other.R` to `helper_functions.R` or anything else http://r-pkgs.had.co.nz/style.html
- `onLoad.R` to `on_attach.R`

3. too many blank code lines in many files, great example:
- https://github.com/ModelOriented/DALEXtra/blob/master/R/other.R#L63
- https://github.com/ModelOriented/DALEXtra/blob/master/R/yhat.R#L76

4. add comments
- https://github.com/ModelOriented/DALEXtra/blob/master/R/create_env.R#L48

5. write `} else {`
- https://github.com/ModelOriented/DALEXtra/blob/master/R/other.R#L18 and more

6. `explain_h2o` has other permutation of parameters than `explain`
https://github.com/ModelOriented/DALEXtra/blob/master/R/explain_h2o.R
same : https://github.com/ModelOriented/DALEXtra/blob/master/R/explain_mljar.R

7. other permutation of parameters in doc and function
- https://github.com/ModelOriented/DALEXtra/blob/master/R/explain_scikitlearn.R

8. other
- lacking documentation https://github.com/ModelOriented/DALEXtra/blob/master/R/print.scikitlearn_set.R
- format of this function is sad, function name same as variable (?) https://github.com/ModelOriented/DALEXtra/blob/master/R/other.R#L85
- `function_name <- function(x)` looks better in the same line and is consistent
https://github.com/ModelOriented/DALEXtra/blob/master/R/explain_mljar.R#L47

**Comment by hbaniecki** [comment]
https://modeloriented.github.io/DALEXtra/reference/explain_mlr.html error on site
