### ISSUE TITLE
h2o::h2o.init()

### ISSUE THREAD

**Issue by Steviey** [ModelOriented/DALEXtra#35]
h2o::h2o.init() fails if there is already an h2o-instance running.

Since in most cases we do preprocessings like partitions etc. with an earlier initiated h2o-instance, and some initiations need more params for ports, logins etc., its generally a bad idea/practise to put h2o::h2o.init() hardcoded in explain_h2o(). 

However, there seems to be a workaround using the regular DALEX::explain() function... 
http://uc-r.github.io/dalex#local

**Comment by pbiecek** [comment]
Thanks
@maksymiuks would you take care of this?

**Comment by maksymiuks** [comment]
Thank You so much! Now it should work perfectly fine!
