### ISSUE TITLE
Error in utils::packageVersion(package) : there is no package called

### ISSUE THREAD

**Issue by hbaniecki** [ModelOriented/DALEXtra#37]
Error when using `explain_mlr()`:
```
library("mlr")
library("DALEX")

task <- mlr::makeClassifTask(id = "task",
                             data = HR,
                             target = "status")

learner <- mlr::makeLearner("classif.kknn",
                            predict.type = "response")

model <- mlr::train(learner, task)

explainer <- DALEXtra::explain_mlr(model = model,
                                   data = HR,
                                   y = HR[,6])
```
In console `utils::packageVersion('kknn')` yields `1.3.1`.

**Comment by maksymiuks** [comment]
Thanks!

Unfortunately, it is the bug on mlr side. I've already reported this, hopefully, they will have it fixed soon.  

By the way, if You use the newest version of DALEXtra, that is available here at Github, package will no longer raise an error if he cannot find a version.
