### ISSUE TITLE
invalid h2o yhat

### ISSUE THREAD

**Issue by hbaniecki** [ModelOriented/DALEXtra#44]
![image](https://user-images.githubusercontent.com/32574004/80493281-7cfed880-8965-11ea-8282-445d495af540.png)

I believe that this should be 3rd column not 2nd. 
https://github.com/ModelOriented/DALEXtra/blob/5e723aa3bea95fa32f4ffe5a84edbc4b0e73fe56/R/yhat.R#L69

**Comment by maksymiuks** [comment]
Thanks
