### ISSUE TITLE
Error in FUN(X[[i]], ...) :    only defined on a data frame with all numeric variables

### ISSUE THREAD

**Issue by hbaniecki** [ModelOriented/DALEXtra#47]
These lines return no columns in my `mlr xgboost` model.
https://github.com/ModelOriented/DALEXtra/blob/1f1d173b1d23e4e5624994a2cf6974a7240ab3ea/R/yhat.R#L33-L35

![image](https://user-images.githubusercontent.com/32574004/81332131-dae89a00-90a2-11ea-8e55-8ce7f98cb304.png)

**Comment by maksymiuks** [comment]
Thanks!

is it a classification or regression model? If a classification is `predict.type` set as `proba`?

**Comment by hbaniecki** [comment]
Classification. I deliberately didn't use `predict.type proba`. I guess that it would be desired to return a `response` column if someone does the same. 

Or return an informative error.

**Comment by maksymiuks** [comment]
Ok. In DALEXtra 0.2.3 there will be if statement for a given situation.

Thanks!
