### ISSUE TITLE
Error while creating anaconda virtual environment using explain_scikitlearn()

### ISSUE THREAD

**Issue by shwetamau** [ModelOriented/DALEXtra#52]
Hi, I trained GBM classifier on structured data, pickled the model and further tried to create virtual environment using the yml file using explain_scikitlearn().  Following is the snippet of code in Python and R: 
Python:
 
![image](https://user-images.githubusercontent.com/66717601/84601384-4f320c80-ae9d-11ea-8bde-5f18d0feae51.png)

R code: 
 
![image](https://user-images.githubusercontent.com/66717601/84601389-5527ed80-ae9d-11ea-9c22-c3aad62a1957.png)

While running the explain_scikitlearn() I am getting following error:
![image](https://user-images.githubusercontent.com/66717601/84601378-43464a80-ae9d-11ea-8e2f-04d25e701bc2.png)

**Comment by maksymiuks** [comment]
Could You please paste .yml file here? How did You obtained it? If ale computations were performed with root env try to make explainer without passing .yml file

**Comment by shwetamau** [comment]
Hi,

First of all thanks for prompt response. I tried creating the .yml file  without root environment. Following is the snippet of .yml file. 

name: shweta
channels:
  - defaults
prefix: C:\Users\shweta.maurya\AppData\Local\Continuum\anaconda3\envs\shweta

Steps followed to create the .yml file:

1.  virtualenv mypython
2. mypython\Scripts\activate
3. pip install pandas (just installing one of the dependencies)
4.  conda env export --name shweta> environment.yml

environment.yml get generated. Further running the R code:

![image](https://user-images.githubusercontent.com/66717601/84668253-07fd5780-af41-11ea-8b3e-4a2f9b41e388.png)

Further getting the error:
![image](https://user-images.githubusercontent.com/66717601/84668541-6591a400-af41-11ea-9e16-3455b48fc4f9.png)

**Comment by maksymiuks** [comment]
Could you please provide me .yml file with saved `shweta` env? You can use my email for that (sz.maksymiuk@gmail.com) Error You get shouldn't happen so I'd like to examine it deeply.

**Comment by maksymiuks** [comment]
Thank You for the file,
for an unknown reason Your yml file is incomplete. and by incomplete I mean it does not even contain Python. It is just empty. Are You sure `shweta` env was used to create that pickle file?

If You did create Your model and pickle file with root anaconda env (default for Jupyter notebook) try evoking
```
explainer_dal <- explain_scikitlearn("gbm.pkl",
                                                         data = X_train_mat, y = y_train,
                                                         label = "gbm")
```
in the fresh session of R. It may work. If not then we will seek for it further

**Comment by shwetamau** [comment]
Hi,

Below is the screenshot of the file which I have shared with you:

![image](https://user-images.githubusercontent.com/66717601/84761631-5402d780-afe7-11ea-8f00-708ac0484ecf.png)
Also I am using the same virtual environment "shweta" to pickle the model. 
If I am using as suggested(without .yml path) it is running perfectly fine because model is built in the same environment but I want to use explain_scikitlearn to for the cross system. For example model is build in system A and have pandas version 1.1 where as I want to use the same model from system A into system B (which has pandas version 1.2 )and try to create virtual environment with the  help of .yml file. Will it solve the problem of cross-environment or not?

**Comment by maksymiuks** [comment]
Yes, it will solve that problem. 
Unfortunately, the file You provides states that `shweta` virtual env is empty. So You need first to install all necessary packages (including python) and then create .yml file. Example of a proper file is below

```
name: myenv
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - certifi=2019.6.16
  - intel-openmp
  - joblib=0.13.2
  - mkl=2019.4
  - mkl-service=2.0.2
  - mkl_fft=1.0.12
  - mkl_random=1.0.2
  - numpy=1.16.4
  - numpy-base=1.16.4
  - pip=19.1.1
  - python=3.6.8
  - scikit-learn=0.21.2
  - scipy=1.2.1
  - setuptools=41.0.1
  - six=1.12.0
  - sqlite=3.28.0
  - wheel=0.33.4
  - pandas=0.24.2
  - keras=2.2.4
  - py-xgboost=0.90
  - libxgboost=0.90
```

**Comment by pbiecek** [comment]
@maksymiuks is it still valid?
if not, let's close it

**Comment by maksymiuks** [comment]
Closed due to lack of response
