### ISSUE TITLE
Error while installing DALEXtra from GitHub: download of package 'vctrs' failed

### ISSUE THREAD

**Issue by FrieseWoudloper** [ModelOriented/DALEXtra#58]
When I try to install DALEXtra from GitHub, I get an error. I run:

`devtools::install_github("ModelOriented/DALEXtra")`

Then I choose to update all packages.

Subsequently I get this error:

```
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/vctrs_0.3.4.zip'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  (converted from warning) cannot open URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/vctrs_0.3.4.zip': HTTP status was '404 Not Found'
Error: Failed to install 'DALEXtra' from GitHub:
  (converted from warning) download of package ‘vctrs’ failed
```

**Comment by maksymiuks** [comment]
Hi,

have You tried installing `vctrs` manually form CRAN? When using auto updater  devtools sometimes fails to detach the package in use and therefore installation is impossible. Try to execute `install.packages("vctrs")`. `blue` package will be probably downloaded as well.

**Comment by maksymiuks** [comment]
Update. Problem is CRAN related, binaries for vctrs are still not ready. Solution that recommends installing it by hand stays valid.

Btw,  vctrs looks like a tibble dependency. Its newest version is not crucial for DALEXtra, You don't have to update right now.

![image](https://user-images.githubusercontent.com/32574056/91977929-a53b8100-ed23-11ea-8a8a-585a743418d2.png)

**Comment by FrieseWoudloper** [comment]
Okay, thank you!
