### ISSUE TITLE
add load_explainer function

### ISSUE THREAD

**Issue by hbaniecki** [ModelOriented/DALEXtra#59]
See https://github.com/ModelOriented/DALEX/issues/357

prototype:

```r
load_explainer <- function(path) {
  ret <- py_load_object(path, pickle = "pickle")
  class(ret) <- c(class(ret), 'explainer')
  ret
}
```

**Comment by maksymiuks** [comment]
Is it still valid?

If so, would exporting this function https://github.com/ModelOriented/DALEXtra/blob/master/R/helper_functions.R#L5-L34 solve the problem?

**Comment by hbaniecki** [comment]
Or we could do:

```r
#' @export
dalex_load_explainer <- function(path) {
  dalex_load_object(path, "explainer")
}
```
