### ISSUE TITLE
Xgboost with sparse matrices

### ISSUE THREAD

**Issue by ghost** [ModelOriented/DALEXtra#60]
Using the explain_xgboost function with a sparse matrix created by sparse.model.matrix(), yilelds the warning

> Preparation of a new explainer is initiated
>   -> model label       :  xgb.Booster  (  default  )
>   -> data              :  33889  rows  87  cols 
>   -> target variable   :  33889  values 
>   -> predict function  :  yhat.xgb.Booster  will be used (  default  )
>   -> predicted values  :  the predict_function returns an error when executed (  WARNING  ) 
> Error in strsplit(model$params$objective, ":", fixed = TRUE) : 
>   non-character argument

Then when inserting the explainer into model_profile yields the error message:

> Error in if (X.model$params$objective == "multi:softprob") { : 
>   argument is of length zero

Are you familiar with the problem, and/or have a solution?

**Comment by maksymiuks** [comment]
Hi,

sadly right now DALEXtra does not work with saparse matrixes. I look closer into it update the package if it's possible.

**Comment by maksymiuks** [comment]
@atlewf Could you please provide me with an example code? I cannot recreate your problem

**Comment by maksymiuks** [comment]
If it comes to explanations and guides over sparse matrices, you will find it here

https://github.com/ModelOriented/DALEX/issues/331
