### ISSUE TITLE
DALEXtra with textual data

### ISSUE THREAD

**Issue by giuliaass** [ModelOriented/DALEXtra#64]
Hi,
is it possible to explain a keras model (CNN) that has textual data as input with DALEX?
I've only seen examples with tabular data.
I preprocess the textual data with word embeddings and use them as a input for my CNN.

Thank you in advance!

**Comment by maksymiuks** [comment]
Inputs for methods served by DALEX and DALEXtra are assumed to be tabular. Could you please elaborate more about the format of your embedded inputs? I'll try to find sth that can help you

**Comment by giuliaass** [comment]
Hi,

To create my code I followed this example:

https://github.com/jjallaire/deep-learning-with-r-notebooks/blob/master/notebooks/6.1-using-word-embeddings.Rmd

First I have a raw text, then I tokenize the data. I'm also using pretrained embeddings.

Thank you! :-)

**Comment by hbaniecki** [comment]
For explanations of neural networks, you can check [Captum](https://captum.ai/) for Python, and a new package [innsight](https://github.com/bips-hb/innsight/) for R.
