### ISSUE TITLE
Which data (training/testing) should be used to build the explainer?

### ISSUE THREAD

**Issue by xiaochi-liu** [ModelOriented/DALEXtra#67]
Hello @maksymiuks,

Many thanks for your great work. Recently I'm learning how to use DALEX and DALEXtra packages to conduct XAI analysis. May I ask you a question about the `explain()` function?

When doing machine learning, we first split the whole dataset into training and testing sets. I have seen most of the tutorials are using the **testing** set to build the explainer (for example this one). This is appropriate when we want to evaluate the model's overall performance.

However, if the analysis purpose is to investigate the relationship between the input features and the target variable (i.e., feature importance, feature effects, and feature interaction), should we use the **training** set to build the explainer?

Your kind guidance is much appreciated!

Best regards,
Xiaochi

**Comment by maksymiuks** [comment]
Hi!

Thank you for your appreciation :) Similar issue was raised on DALEX repository, please check it and the article that is linked there :)

But tl;dr - it depends

Let me know if the above issue answers your questions

Best
Szymon

**Comment by xiaochi-liu** [comment]
Thank you very much @maksymiuks!

I‘ve found [the article](https://arxiv.org/abs/2105.13787) and will do a close read on it.
