### ISSUE TITLE
Error when using `mlr3::Autotuner`.

### ISSUE THREAD

**Issue by vitaminasnow** [ModelOriented/DALEXtra#69]
when I try to use `DALEXtra::explain_mlr3` and then `DALEX::model_profile()` with a trained `AutoTuner$new()`, I get 
```
Error: Input task during prediction of int_to_num does not match input task during training.
This happened PipeOp int_to_num's $predict()
```
as an error message.
Please, notice that this error does not appear when doing a regular procedure within mlr3 --- Train a model, and then use it for predictions.

**Comment by hbaniecki** [comment]
Hi @vitaminasnow, does https://github.com/ModelOriented/DALEXtra/issues/71 by any chance fix your issue? 

You can test the development version of `DALEXtra` using `devtools::install_github("ModelOriented/DALEXtra")`
