### ISSUE TITLE
Check / auto-convert type of `explain_mlr3` input

### ISSUE THREAD

**Issue by mb706** [ModelOriented/DALEXtra#71]
The `model` input of `explain_mlr3` should be an `mlr3` `Learner` object, but there are a few things in `mlr3` that can be converted to `Learner`s automatically. Consider using `mlr3::as_learner(model)` instead of just `model` in the `explain()` call here: https://github.com/ModelOriented/DALEXtra/blob/bf480f8e315455c06c14cd86dc9d47cfb5dfa383/R/explain_mlr3.R#L49-L68

or alternatively, `mlr3::assert_learner()` if you want to force your users to do the conversion for themselves. (Imho `as_learner()` would fit more naturally with how `mlr3` behaves otherwise).

This bug was caused by someone accidentally using a `Graph`, expecting it to be converted to a `Learner` internally: https://github.com/mlr-org/mlr3pipelines/issues/642

**Comment by hbaniecki** [comment]
@maksymiuks can we add `mlr3::as_learner(model)` here?

**Comment by hbaniecki** [comment]
Hi @mb706, looking at https://github.com/mlr-org/mlr3/blob/main/R/as_learner.R, the `as_learner()` function seems not to be doing much, or am I wrong?

EDIT. nvm, I see now, e.g. https://github.com/mlr-org/mlr3pipelines/blob/e55b0a93b11c109534d5fd1db3b0d47a0a7e53ed/R/GraphLearner.R#L209-L217

**Comment by hbaniecki** [comment]
Thanks
