### ISSUE TITLE
model_profile throws error when explaining some columns

### ISSUE THREAD

**Issue by zachbogart** [ModelOriented/DALEXtra#72]
Going through TidyModels in R and got to a super cool section on [partial dependence profiles ](https://www.tmwr.org/explain.html#building-global-explanations-from-local-explanations). I am having trouble reproducing the code on partial dependence profiles, specifically the `model_profile` function from DALEX throws an error about loss of precision for the column the text wants to explain, Year_Built.

- I tried converting the `Year_Built` column from an integer to a double but I get the same error:

```
> pdp_age <- model_profile(explainer_rf, N = 500, variables = "Year_Built")
Error in `stop_vctrs()`:
! Can't convert from `Year_Built` <double> to `Year_Built` <integer> due to loss of precision.
• Locations: 2, 3, 5, 13, 14, 49, 53, 72, 73, 75, 83, 84, 119, 123, 142, 143, 145, 153, 154, 189, 193, 212, ...
Run `rlang::last_error()` to see where the error occurred.
```

- Strangely, the code above does seem to run for other columns, like `Latitude`

I'm wondering if it might be a bug in `model_profile`

- Started as a [discussion in the R Community Forum](https://community.rstudio.com/t/trouble-with-partial-dependence-profiles-in-tidy-models-with-r/131297), shows full ML code taken from Tidy Models with R

**Comment by hbaniecki** [comment]
Hello, I know the reason for this error. Basically, `model_profile()` creates `variable_splits` - points/domain, in which the profile will be calculated, automatically using either quantiles or uniform distribution. This functionality is hidden in the basic DALEX package (https://modeloriented.github.io/DALEX/reference/model_profile.html), but the parameters are actually passed down to `ingredients`:
- https://modeloriented.github.io/ingredients/reference/calculate_variable_split.html
- https://modeloriented.github.io/ingredients/reference/partial_dependence.html

Having debugged the code, I believe that the model you use treats `integer` and `double` values differently; hence, if you use an `integer` variable, but `DALEX` creates `double` variable splits, the model returns an error in calculating the prediction.

Solution 1. Pass custom `variable_splits` to `model_profile`:
```r
pdp_age <- model_profile(
  explainer_rf, 
  N = 500,
  variables = "Year_Built",
  variable_splits = list("Year_Built"=unique(vip_train$Year_Built))
)
plot(pdp_age)
```

Solution 2. Don't distinguish between `double`/`integer` in the modelling by adding `Year_Built = as.double(Year_Built)`:

```r
library(tidymodels)
library(DALEXtra)
data(ames)
ames <- mutate(ames, Sale_Price = log10(Sale_Price), Year_Built = as.double(Year_Built))

# split the data
set.seed(502)
ames_split <- initial_split(ames, prop = 0.80, strata = Sale_Price)
ames_train <- training(ames_split)
ames_test  <-  testing(ames_split)

# recipe preprocessing and what is being predicted
ames_rec <- 
  recipe(Sale_Price ~ Neighborhood + Gr_Liv_Area + Year_Built + Bldg_Type + 
           Latitude + Longitude, data = ames_train) %>%
  step_log(Gr_Liv_Area, base = 10) %>% 
  step_other(Neighborhood, threshold = 0.01) %>% 
  step_dummy(all_nominal_predictors()) %>% 
  step_interact( ~ Gr_Liv_Area:starts_with("Bldg_Type_") ) %>% 
  step_ns(Latitude, Longitude, deg_free = 20)

# random forest
rf_model <- 
  rand_forest(trees = 1000) %>% 
  set_engine("ranger") %>% 
  set_mode("regression")

# workflow, add formula rather than recipe
# minimal to no preprocessing needed
rf_wflow <- 
  workflow() %>% 
  add_formula(
    Sale_Price ~ Neighborhood + Gr_Liv_Area + Year_Built + Bldg_Type + 
      Latitude + Longitude) %>% 
  add_model(rf_model) 

# normal fitting example
rf_fit <- rf_wflow %>% 
  fit(ames_train)

# isolate features
vip_features <- c("Neighborhood", "Gr_Liv_Area", "Year_Built", 
                  "Bldg_Type", "Latitude", "Longitude")
vip_train <- 
  ames_train %>% 
  select(all_of(vip_features))

# create a DALEX explainer
explainer_rf <- 
  explain_tidymodels(
    rf_fit, 
    data = vip_train, 
    y = ames_train$Sale_Price,
    label = "random forest",
    verbose = T
  )

predict(explainer_rf, vip_train)
# this DOES work on Year_Built
set.seed(1805)
pdp_age <- model_profile(
  explainer_rf, 
  N = 500,
  variables = "Year_Built"
  # variable_splits = list("Year_Built"=unique(vip_train$Year_Built))
)
plot(pdp_age)
```
