### ISSUE TITLE
Possible to move reticulate to Suggests?

### ISSUE THREAD

**Issue by juliasilge** [ModelOriented/DALEXtra#87]
Hello! 👋 Thanks so much for all your great work on this package.

I wanted to ask if you all would be open to moving reticulate to Suggests. This is motivated in particular by how [Posit Connect](https://posit.co/products/enterprise/connect/) sets up environments for content that requires reticulate (installs Python and tried to create an environment), but I think this will come into play on other deployment targets as well. The idea here is that if you are using tidymodels, you don't need Python and reticulate installed, but if you are using a model like keras, you already have Python and reticulate from dealing with the model itself.

I took a look at [how you are using reticulate](https://github.com/ModelOriented/DALEXtra/search?q=reticulate), and I _think_ you could move reticulate to Suggests if you wrapped calls in `rlang::is_installed()` or used a base R equivalent. For example, your `.onLoad()` could become:

```r
# Check if conda is present. If not, warning will be raised.

.onAttach <- function(libname, pkgname) {
  if (rlang::is_installed("reticulate")) {
      is_conda <- try(reticulate::conda_binary(), silent = TRUE)
      if(inherits(is_conda, "try-error")) {
        packageStartupMessage("Anaconda not found on your computer. Conda related functionality such as create_env.R and condaenv and yml parameters from explain_scikitlearn will not be available")
      }
  }
}
```

What would you think about a change like this?

**Comment by maksymiuks** [comment]
Hi @juliasilge 

First of all thanks for your appreciation of our work :)

Honestly, I was thinking about it before and I'm glad you've opened this issue prompting me to rethink this design. Over they years this package has evolved and I agree that keeping `reticulate` as a hard dependency does not have much sense nowadays. Therefore I'll be happy to make this change. Will ping you once it it done :)

**Comment by maksymiuks** [comment]
Hi @juliasilge 

It took a while but DALEXtra version with reticulate moved to suggests has been pushed to CRAN last night alongside some refactor :) Let me know if I can help you with anything else!

**Comment by juliasilge** [comment]
This is such great news @maksymiuks! 🙌 Thank you so much for working on this; it will make deploying explainers for tidymodels much easier. I'll let you know if we run into any other challenges along these lines.
