### ISSUE TITLE
Parallel processing

### ISSUE THREAD

**Issue by williamshell** [ModelOriented/DALEXtra#88]
Hi, everyone, 

I wonder to know that wether the DALEXtra can support the parallel processes with the doParallel  package? I run the codes bleow and codes [here](https://modeloriented.github.io/DALEXtra/reference/explain_tidymodels.html), the function model_parts do not doing parallel processes, even that the fucntion parallel and processes  are turned on.  Do anyone can help me?

```
library(doParallel)
library(DALEXtra)

cl <- makePSOCKcluster(24)
registerDoParallel(cl)
explainer <- explain_tidymodels(model_fitted, data = titanic_imputed, y = titanic_imputed$survived)
feature_importance <- model_parts(explainer, loss_function = loss_cross_entropy, parallel = TRUE, processes = 8, B = 100, type = "difference")
```

**Comment by maksymiuks** [comment]
Hi @williamshell

First of all thanks for reaching out to me. First of all, DALEXtra does not really implement `model_parts` method. It is only an interface allowing out-of-the-box support for statistical models created using more complicated frameworks (like tidymodels). Actual implementation happens in DALEX/ingredients packages.

That being said, currently, there is no option to run explanations in parallel processes. The function currently is a simple one-thread loop. Re-engineering this (possibly supporting parallelization) is something authors aim for in 3.0 release of DALEX https://github.com/ModelOriented/DALEX/issues/501

**Comment by williamshell** [comment]
> Hi @williamshell
> 
> First of all thanks for reaching out to me. First of all, DALEXtra does not really implement `model_parts` method. It is only an interface allowing out-of-the-box support for statistical models created using more complicated frameworks (like tidymodels). Actual implementation happens in DALEX/ingredients packages.
> 
> That being said, currently, there is no option to run explanations in parallel processes. The function currently is a simple one-thread loop. Re-engineering this (possibly supporting parallelization) is something authors aim for in 3.0 release of DALEX [ModelOriented/DALEX#501](https://github.com/ModelOriented/DALEX/issues/501)

Hi @maksymiuks ，

Your response is greatly appreciated. I am looking forward to the 3.0 release of DELEX.
